-- Update password hashes for demo users
-- These are proper BCrypt hashes generated by PasswordUtil
-- Run this script to fix login issues

USE timesheet_db;

-- Update admin password (admin123)
UPDATE users
SET password_hash = '$2a$12$w6KptETsNNA3xoxvtR7SBO9vth.zI.SqmeAlHshGey7RpmWe/WRgu'
WHERE username = 'admin';

-- Update project manager password (manager123)
UPDATE users
SET password_hash = '$2a$12$Yds1ilYnUSlSKIZkvT5ode/h3dxz2Gxmj7yrexdhdukOt7t..QqqK'
WHERE username = 'jsmith';

-- Update employee password (employee123)
UPDATE users
SET password_hash = '$2a$12$LltMDXJXuf93ZXp5s7aFiOoow12fWhFQE7bfHOzs3mOhDJ0E8rLQK'
WHERE username = 'mjohnson';

-- Verify updates
SELECT username, email, role, is_active,
       SUBSTRING(password_hash, 1, 20) as hash_preview
FROM users
WHERE username IN ('admin', 'jsmith', 'mjohnson');

COMMIT;